#### add paths to /etc/profile file to all users...
####
#### ...add /sbin folder and anaconda3 (depends on anaconda path installation) to PATH...
PATH="/sbin:/opt/anaconda3/bin:$PATH"
####
#### ...add this path to create conda environments in anaconda path installation...
export CONDA_ENVS_PATH="/opt/anaconda3/envs"
